config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :images
  resources :values
  resources :users
  resources :sessions

  root 'main#index'
  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'

  match 'work', to: 'work#index',via: 'get'
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme', to: 'work#choose_theme', via: :get
  match 'rate', to: 'work#rate', via: :get
  match 'display_theme', to: 'work#display_theme', via: :post, as: :js
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do
    match 'next_image', to: 'api#next_image', via: :get
    match 'prev_image', to: 'api#prev_image', via: :get
    match 'save_value', to: 'api#save_value', via: :get
  end

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'

end

app/views/shared/_footer.html.haml
%div.footer
  %span= "✍(◔◡◔) RoR app v1.01"

  %ul
    %li= link_to 'Index', main_index_path
    %li= link_to 'Contacts', main_contacts_path
    %li= link_to 'Help', main_help_path
    %li= link_to 'About', main_about_path

app/views/shared/_header.html.haml
%ul.nav-header
  %li.nav-header__link-btn{:class => cp(root_path)}=link_to t('shared.header.index'), root_path
  %li.nav-header__link-btn{:class => cp(work_path)}=link_to t('shared.header.work'), work_path
  %li.nav-header__link-btn{:class => cp(main_about_path)}=link_to t('shared.header.about'), main_about_path
  %li.nav-header__link-btn{:class => cp(images_path)}=link_to t('shared.header.images'), images_path
  %div.nav-header__link-btn.locale
    %span{:class => dt(:ru)}= link_to t('locale.ru'), locale: :ru
    %span{:class => dt(:en)}= link_to t('locale.en'), locale: :en
  - if signed_in?
    %div.logged{:email => current_user.email}
      = gravatar_for current_user
  - if signed_in?
    %button.nav-header__link-btn
      = link_to t('.sign_out'), signout_path, method: "delete"
  - else
    %button.nav-header__link-btn=link_to t('.sign_in'), signin_path